ignored = ["github.com/kubeless/kubeless/pkg/functions"]

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/glendc/go-external-ip"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.3.0"
